### ISSUE TITLE
`nu_LSO` is not used anywhere

### ISSUE THREAD

**Issue by jose-d** [ippocratiss/EMRI_MC#3]
while creating the right project files structure, I realized that `nu_LSO` is not used anywhere.

Is it intentional?

https://github.com/ippocratiss/EMRI_MC/blob/425697121ae2679c9d94005d7e9f3e83971c0744/mcmc.py#L125

**Comment by ippocratiss** [comment]
It is used as initial condition in the ODE solver.

**Comment by jose-d** [comment]
cannot be that it takes the value from here
https://github.com/ippocratiss/EMRI_MC/blob/425697121ae2679c9d94005d7e9f3e83971c0744/global_parameters.py#L71
and the value calculated in iterate_mcmc() is never used?

**Comment by ippocratiss** [comment]
OK, will be removed.
